apiVersion: v1
kind: Pod
metadata:
  name: pod-with-env
spec:
  containers:
    - name: myenv
      image: alpine:latest
      command: ["/bin/sh"]
      args: ["-c","while true; do sleep 30; done"]
      env:
      - name: NEW_NAME
        value: tianzhiqiang
      - name: DOG_NAME
        value: wangcai
